# Generated by Django 5.1.5 on 2025-01-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamSpliceBolted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_size', models.CharField(max_length=50)),
                ('material', models.CharField(default='Fe 410 WA', max_length=50)),
                ('weld_type', models.CharField(default='Fillet Weld', max_length=50)),
                ('bending_moment', models.FloatField()),
                ('shear_force', models.FloatField()),
                ('axial_force', models.FloatField()),
                ('flange_preference', models.CharField(max_length=50)),
                ('flange_thickness', models.FloatField()),
                ('web_thickness', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
