# Generated by Django 5.1.5 on 2025-01-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamsplicebolted',
            name='created_at',
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='flange_plate_width',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='member_capacity',
            field=models.FloatField(default=1725),
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='web_plate_height',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='beamsplicebolted',
            name='flange_preference',
            field=models.CharField(default='Outside', max_length=20),
        ),
    ]
