# Generated by Django 5.1.5 on 2025-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_remove_beamsplicebolted_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamsplicebolted',
            name='flange_plate_width',
        ),
        migrations.RemoveField(
            model_name='beamsplicebolted',
            name='web_plate_height',
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='design_status',
            field=models.CharField(default='SAFE', max_length=20),
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='flange_plate_thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='web_plate_thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beamsplicebolted',
            name='weld_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beamsplicebolted',
            name='axial_force',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beamsplicebolted',
            name='flange_thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beamsplicebolted',
            name='member_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beamsplicebolted',
            name='web_thickness',
            field=models.FloatField(default=0),
        ),
    ]
